### PR TITLE
ISO 8601 for date formats and a reversepfp command

### PR DESCRIPTION
**Pull request by Moe-Szyslak**
Unified the date formats under the infraction date in the history embed to the ISO 8601 standard of yyyy-MM-dd as it is under the user join date and user creation date

### CODE REVIEW

**Comment by Moe-Szyslak** [comment]
Also added a reverse profile picture command which takes a user and returns the url of the reverse search on their profile picture

**Comment by joshthewall** [comment]
The note date is also in the format `dd/MM/yyy`, so maybe you want to change that too.

**Comment by Moe-Szyslak** [comment]
Good spot @joshthewall I've made that change

**Comment by AberrantFox** [comment]
Would rather the date format is dd/MM/yyyy

**Pull request closed without merging**
